GangwonGangwon_trip_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('scraper/', include('scraper.urls')),
    path('', include('main.urls')),
]

main/main/urls.py
from django.urls import path
from .views import index, about, post, contact, chart_data,recommend

app_name = "main"
urlpatterns = [
    path('', index , name='index'),
    path('tour2/', about , name='about'),
    # path('tour3/', post , name='post'),
    path('tour3/', chart_data , name='post'),
    # path('tour3/',prediction, name='prediction'),
    path('tour4/', contact , name='contact'),
    path('recommend/',recommend, name ="recommend")
    ]
    

main/urls.py
from django.urls import path
from .views import index, about, post, contact, chart_data,prediction, recommend

app_name = "main"
urlpatterns = [
    path('', index , name='index'),
    path('tour2/', about , name='about'),
    # path('tour3/', post , name='post'),
    path('tour3/', chart_data , name='post'),
    path('tour4/', contact , name='contact'),
    path('recommend/', recommend , name='recommend'),
    ]
    

main/main/models.py
# Create your models here.

from django.db import models
from django.utils.timezone import now

# Create your models here.

class TripNews(models.Model):
    news_url = models.CharField(max_length=200, unique=True,  default='')
    title = models.CharField(max_length=200, default='')
    loc = models.CharField(max_length=100,  default='')
    date = models.CharField(max_length=10,  default='')
    likeCnt = models.CharField(max_length=10, null=True)
    shareCnt = models.CharField(max_length=10, null=True)
    readCnt = models.CharField(max_length=10, null=True)
    created_at = models.DateTimeField(default=now)

    def __str__(self):
        return f'{self.title}--{self.loc}--{self.date}--{self.created_at}'

class NewsSummery(models.Model):
    post_url = models.CharField(max_length=200, null=True)
    card_title = models.CharField(max_length=100, null=True)
    summary_info = models.CharField(max_length=10000, null=True)
    img_url = models.CharField(max_length=200, null=True)

    def __str__(self):
        return f'{self.pk}--{self.card_title}'


class InputKeyword(models.Model) :
    keyword = models.CharField(max_length=100)
    count = models.IntegerField()

main/models.py
# Create your models here.

from django.db import models
from django.utils.timezone import now

# Create your models here.

class TripNews(models.Model):
    news_url = models.CharField(max_length=200, unique=True,  default='')
    title = models.CharField(max_length=200, default='')
    loc = models.CharField(max_length=100,  default='')
    date = models.CharField(max_length=10,  default='')
    likeCnt = models.CharField(max_length=10, null=True)
    shareCnt = models.CharField(max_length=10, null=True)
    readCnt = models.CharField(max_length=10, null=True)
    created_at = models.DateTimeField(default=now)

    def __str__(self):
        return f'{self.title}--{self.loc}--{self.date}--{self.created_at}'

class NewsSummery(models.Model):
    post_url = models.CharField(max_length=200, null=True)
    card_title = models.CharField(max_length=100, null=True)
    summary_info = models.CharField(max_length=10000, null=True)
    img_url = models.CharField(max_length=200, null=True)

    def __str__(self):
        return f'{self.pk}--{self.card_title}'

class InputKeyword(models.Model) :
    keyword = models.CharField(max_length=100)
    count = models.IntegerField()

main/main/views.py
from django.shortcuts import redirect, render
from .models import TripNews, NewsSummery, InputKeyword
import pandas as pd
import mlflow
import warnings
import pickle
import numpy as np

# Create your views here.


def about(request):
    datas = TripNews.objects.all().order_by("created_at")
    summ = NewsSummery.objects.all()
    return render(request, 'about.html', {'news' : datas, 'summ': summ})


def index(request):
    return render(request, 'index.html')
def post(request):
    return render(request, 'post.html')
def contact(request):
    return render(request, 'contact.html')
def recommend(request):
    return render(request, 'recommend.html')


def chart_data(request):
    df = pd.read_csv("./data/place_review_cnt_data.csv")
    df2 = pd.read_csv('./data/word_cnt_info.csv')
    word_dict = pd.read_csv("./data/word_list.csv")
    cnt_review = list(df['리뷰수'][:7])
    names = list(df['장소'][:7])
    cnt_word = list(df2['빈도수'][:7])
    words = list(df2['단어'][:7])
    word_dict = list(word_dict["장소"])
    word_dict = word_dict
    input_keywords = InputKeyword.objects.all().order_by("-count")
    if len(input_keywords) < 7:
        input_keywords = input_keywords[:len(input_keywords)]
    else:
        input_keywords = input_keywords[:7]
        
    if request.method == 'POST':
        selected_place =  request.POST.getlist("CheckboxName")
        print(selected_place)

        if selected_place != []:    # 선택한 단어 DB에 저장
            for keyword in selected_place:
                if InputKeyword.objects.filter(keyword = keyword).count() != 0: # 기존 데이터가 존재할 경우 +1
                    update_row = InputKeyword.objects.get(keyword = keyword)
                    update_row.count = update_row.count +1
                    update_row.save()
                else:
                    InputKeyword(keyword = keyword, count = 1).save()

        place_list = pd.read_csv("./data/Gangwon_place_list.csv", encoding ="utf-8-sig")
        user = pd.read_csv("./data/user_answer_form.csv")
        for place in selected_place:
            if place in user.columns:
                user.at[0,place] = 1
        loaded_model = pickle.load(open('./models/model.pkl', 'rb'))
        pred = loaded_model.predict(user)
        predict_places = []
        for loc in pred:
            predict_places.append(place_list.iloc[loc,:])
        
        # print(predict_places[0].str.split(" ")[0])
        # print('type:', type(predict_places[0].str.split(" ")[0]))            
        predict_places = predict_places[0].str.split(" ")[0]
        if type(predict_places) == float:
            predict_places = ["키워드를 다시 입력해주세요"] 
        else : 
            pred_place = predict_places[0]
        
        return render(request,"recommend.html",{"predict_places" : predict_places})

    else :    
        return render(request, 'post.html',
                        {'cnt_review': cnt_review, 'names' : names, 'cnt_word' : cnt_word, 'words' : words,"word_dict" : word_dict,  'input_keywords' : input_keywords
                        })

main/views.py
from django.shortcuts import redirect, render
from .models import TripNews, NewsSummery, InputKeyword
import pandas as pd
import mlflow
import warnings
import pickle
import numpy as np
​
# Create your views here.
​
​
def about(request):
    datas = TripNews.objects.all().order_by("created_at")
    summ = NewsSummery.objects.all()
    return render(request, 'about.html', {'news' : datas, 'summ': summ})
​
​
def index(request):
    return render(request, 'index.html')
def post(request):
    return render(request, 'post.html')
def contact(request):
    return render(request, 'contact.html')
def recommend(request):
    return render(request, 'recommend.html')
​
​
def chart_data(request):
    df = pd.read_csv("./data/place_review_cnt_data.csv")
    df2 = pd.read_csv('./data/word_cnt_info.csv')
    word_dict = pd.read_csv("./data/word_list.csv")
    cnt_review = list(df['리뷰수'][:7])
    names = list(df['장소'][:7])
    cnt_word = list(df2['빈도수'][:7])
    words = list(df2['단어'][:7])
    word_dict = list(word_dict["장소"])
    word_dict = word_dict
    input_keywords = InputKeyword.objects.all().order_by("-count")
    if len(input_keywords) < 7:
        input_keywords = input_keywords[:len(input_keywords)]
    else:
        input_keywords = input_keywords[:7]
        
    if request.method == 'POST':
        selected_place =  request.POST.getlist("CheckboxName")
        print(selected_place)
​
        if selected_place != []:    # 선택한 단어 DB에 저장
            for keyword in selected_place:
                if InputKeyword.objects.filter(keyword = keyword).count() != 0: # 기존 데이터가 존재할 경우 +1
                    update_row = InputKeyword.objects.get(keyword = keyword)
                    update_row.count = update_row.count +1
                    update_row.save()
                else:
                    InputKeyword(keyword = keyword, count = 1).save()
​
        place_list = pd.read_csv("./data/Gangwon_place_list.csv", encoding ="utf-8-sig")
        user = pd.read_csv("./data/user_answer_form.csv")
        for place in selected_place:
            if place in user.columns:
                user.at[0,place] = 1
        loaded_model = pickle.load(open('./models/model.pkl', 'rb'))
        pred = loaded_model.predict(user)
        predict_places = []
        for loc in pred:
            predict_places.append(place_list.iloc[loc,:])
        
        # print(predict_places[0].str.split(" ")[0])
        # print('type:', type(predict_places[0].str.split(" ")[0]))            
        predict_places = predict_places[0].str.split(" ")[0]
        if type(predict_places) == float:
            predict_places = ["키워드를 다시 입력해주세요"] 
        else : 
            pred_place = predict_places[0]
        
        return render(request,"recommend.html",{"predict_places" : predict_places})
​
    else :    
        return render(request, 'post.html',
                        {'cnt_review': cnt_review, 'names' : names, 'cnt_word' : cnt_word, 'words' : words,"word_dict" : word_dict,  'input_keywords' : input_keywords
                        })

main/templates/about.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        {% comment %} mini_project {% endcomment %}
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
        

        <!-- fontawesome kit -->
        <script src="https://kit.fontawesome.com/a2d15513fa.js" crossorigin="anonymous"></script>
        <title>visit korea</title>
        
        
        
  
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>visit gangwon</title>
        <link rel="icon" type="image/x-icon" href="./assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css'%}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'main:index' %}">Travearch</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                      <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'main:index' %}">home</a></li>
                      <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'main:about' %}">news</a></li>
                      <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'main:post' %}">recommend</a></li>
                      <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'main:contact' %}">about</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'img/about-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>최신여행지정보</h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container mt-5">
          <table class="table table-hover">
              <thead>
                <tr>
                  <th scope="col">기사 바로가기</th>
                  <th scope="col">제목</th>
                  <th scope="col">좋아요</th>
                  <th scope="col">조회수</th>
                  <th scope="col">수정일</th>
                </tr>
              </thead>
              <tbody>
                  {% for data in news %}
                <tr>
                  <td class="center"><a role="button" class="btn btn-outline-secondary" href="{{ data.news_url }}"><i class="fa-solid fa-arrow-up-right-from-square"></i></a></td>
                  <td><a role="button" class="text-dark" data-toggle="modal" href="#myModal-{{ data.pk }}" style="text-decoration:none;">{{ data.title }}</a></td>
                  <td class="center"><span>{{ data.likeCnt }}</span></td>
                  <td class="center"><span>{{ data.readCnt }}</span></td>
                  <td><span>{{ data.date }}</span></td>
                  <tr>
                  <!--요약보기 모달창-->
                  <!-- Modal -->
                    <div class="modal fade" id="myModal-{{ data.pk }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                      <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                          <div class="modal-header">
                            <span class="container"><h4 class="modal-title" id="myModalLabel">기사 요약보기</h4></span>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            </div>
                          <div class="modal-body">
                            <div class="container-fluid">
                              <h5 class="text-center">{{data.title}}</h5>
                              <div class="text-center">
                                <small class="text-muted">{{data.loc}}</small></div>
                                <hr>
                                {% for s in summ %}
                                {% if s.post_url == data.news_url %}
                              <div class="row">
                                <div class="col-4">
                                  <div class="img h-100" style="background-image: url('{{ s.img_url }}'); background-size: cover; "></div>
                                </div>
                                <div class="col-8">
                                  <span class="font-weight-bold">{{ s.card_title }}</span><br>
                                  <span><small>{{ s.summary_info }}</small></span>
                                <hr>
                                </div>
                              </div>
                              {%endif%}
                              {% endfor %}
                            </div>
                          </div>
                          <a role="button" href="{{ data.news_url }}" class="btn btn-outline-dark btn-lg btn-block">기사 전문 보기 ></a>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
                          </div>
                        </div>
                      </div>
                    </div>

                </tr>
                </tr>
                {% endfor %}
              </tbody>
          </table>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
        
        
        
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js'%}"></script>
    </body>
</html>

main/templates/contact.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>visit gangwon</title>
        <link rel="icon" type="image/x-icon" href="./assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css'%}" rel="stylesheet" />

        <!-- about_part -->    
        <link rel="stylesheet" href="{% static 'css/about_animate.css'%}">
        <link rel="stylesheet" href="{% static 'css/about.css'%}">

    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav" style="flex:none;">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'main:index' %}">Travearch</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'main:index' %}">home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'main:about' %}">news</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'main:post' %}">recommend</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'main:contact' %}">about</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'img/about-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading" >
                            <h1 style="color:white; font-size: 5rem; font-weight:700;">About Us</h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <section class="ftco-section">
                <div class="container">
                    <div class="row d-md-flex">
                        <div class="col-md-6 ftco-animate img about-image" style="background-image: url({% static 'img/bg-post.jpg' %}); background-size: cover;">
                        </div>
                        <div class="col-md-6 ftco-animate p-md-5">
                            <div class="row">
                          <div class="col-md-12 nav-link-wrap mb-5">
                            <div class="nav ftco-animate nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                              <a class="nav-link active" id="v-pills-whatwedo-tab" data-toggle="pill" href="#v-pills-whatwedo" role="tab" aria-controls="v-pills-whatwedo" aria-selected="true" style="background-Color:gray;">팀원소개</a>
        
                              <a class="nav-link" id="v-pills-mission-tab" data-toggle="pill" href="#v-pills-mission" role="tab" aria-controls="v-pills-mission" aria-selected="false" style="background-Color:gray;">추진배경</a>
        
                              <a class="nav-link" id="v-pills-goal-tab" data-toggle="pill" href="#v-pills-goal" role="tab" aria-controls="v-pills-goal" aria-selected="false" style="background-Color:gray;">서비스</a>
                            </div>
                          </div>
                          <div class="col-md-12 d-flex align-items-center">
                            
                            <div class="tab-content ftco-animate" id="v-pills-tabContent">
        
                              <div class="tab-pane fade show active" id="v-pills-whatwedo" role="tabpanel" aria-labelledby="v-pills-whatwedo-tab">
                                  <div>
                                    
                                    <p><h3>한호</h3><h6 class="mb-5">데이터 분석, ML 모델 제작</h6></p>
                                    <p><h3>진수현</h3><h6 class="mb-5">DB, 서버관리</h6></p>
                                    <p><h3>왕경훈</h3><h6 class="mb-5">웹 페이지/UI</h6></p>
                                    </div>
                              </div>
        
                              <div class="tab-pane fade" id="v-pills-mission" role="tabpanel" aria-labelledby="v-pills-mission-tab">
                                <div>
                                    <h2 class="mb-4">개요</h2>
                                      <p >지난 2년간 코로나 시국으로 인해 국내여행 횟수가 감소했고
                                        코로나로 인한 사회적 거리두기 해제 이후 2022년 첫 여름으로 
                                        휴가를 떠나는 여행객이 증가할것으로 예상됩니다. 
                                    <p >또한, 코로나 19이후 재방문 지역 1순위가 강원도라는 점과 리뷰의 중요성이 점점 증가하고 있다는 점을
                                        고려해 "리뷰를 통한 강원도 관광지 추천" 이라는 서비스를 개발 하게되었습니다. 
                                        </p>
                                    
                                    </div>
                              </div>
        
                              <div class="tab-pane fade" id="v-pills-goal" role="tabpanel" aria-labelledby="v-pills-goal-tab">
                                <div>
                                    <h2 class="mb-4">리뷰분석을 통한 강원도 관광지 추천</h2>
                                      <p>관광사이트 리뷰분석을 통해 최적의 관광지 추천 서비스를 제공하고 있습니다. 사용자가 키워드를 선택해 관광지 추천을 받을 수 있고 최신 여행지 정보도 제공하고 있습니다.</p>
                                    
                                    </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                </div>
            </section>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js'%}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
        
        <!-- about_part -->
        {% static 'js/scripts.js'%}
        <script src="{% static 'js/about/jquery.min.js'%}"></script>
        <script src="{% static 'js/about/jquery-migrate-3.0.1.min.js'%}"></script>  
        <script src="{% static 'js/about/bootstrap.min.js'%}"></script> 
        <script src="{% static 'js/about/jquery.waypoints.min.js'%}"></script>
        <script src="{% static 'js/about/jquery.stellar.min.js'%}"></script>
        <script src="{% static 'js/about/owl.carousel.min.js'%}"></script> 
        <script src="{% static 'js/about/aos.js'%}"></script>
        <script src="{% static 'js/about/scrollax.min.js'%}"></script>
        <script src="{% static 'js/about/main.js'%}"></script>


    </body>
</html>